### ISSUE TITLE
Doublons dans le fichier de classe

### ISSUE THREAD

**Issue by morel-olivier** [heig-vd-tin/template-tb#2]
Dans le fichier heig-tb.cls, un institut et une orientation sont écrites à double.

A la ligne 60, l'institut Comatec est déclaré 2 fois.
A la ligne 113, l'orientation Mécatronique est déclarée 2 fois.

**Comment by yves-chevallier** [comment]
Très bonne remarque. Vous pouvez si vous le souhaitez faire une PR avec un fix
________________________________
From: morel.olivier ***@***.***>
Sent: Thursday, April 27, 2023 9:36:12 AM
To: HEIG-VD/template-tb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HEIG-VD/template-tb] Doublons dans le fichier de classe (Issue #2)


Dans le fichier heig-tb.cls, un institut et une orientation sont écrites à double.

A la ligne 60, l'institut Comatec est déclaré 2 fois.
A la ligne 113, l'orientation Mécatronique est déclarée 2 fois.
