### ISSUE TITLE
Table des matières Appendices

### ISSUE THREAD

**Issue by Kenzi-Antonin** [heig-vd-tin/template-tb#7]
Dans la table des matières, la partie "Annexes" apparaît comme "Appendices"  
Proposition d'ajout de ligne 397 du fichier heig-tb.cls :

```
\renewcommand\appendixtocname{Annexes}
```
Cela règle le problème chez moi

**Comment by yves-chevallier** [comment]
Le terme Appendices est correct du point de vue français. 

https://guideepep.jimdofree.com/%C3%A9tudiants-tes/pr%C3%A9sentation-des-travaux/annexes-et-appendices/#:~:text=Les%20annexes%20et%20les%20appendices,que%20les%20appendices%20sont%20facultatifs.

Est-ce le mot qui ne vous convenait pas ?

**Comment by Kenzi-Antonin** [comment]
Je comprend mieux rend la nuance, merci
